/**
 *    Alms class
 */
export const FETCH_ALPS_CLASS_LIST_REQUEST =
  'board/CourseDetailPage/FETCH_ALPS_CLASS_LIST_REQUEST';
export const FETCH_ALPS_CLASS_LIST_FAIL =
  'board/CourseDetailPage/FETCH_ALPS_CLASS_LIST_FAIL';
export const FETCH_ALPS_CLASS_LIST_SUCCESS =
  'board/CourseDetailPage/FETCH_ALMS_CLASS_LIST_SUCCESS';

export const FETCH_ALPS_CLASS_STUDENT_LIST_REQUEST =
  'board/CourseDetailPage/FETCH_ALPS_CLASS_STUDENT_LIST_REQUEST';
export const FETCH_ALPS_CLASS_STUDENT_LIST_FAIL =
  'board/CourseDetailPage/FETCH_ALPS_CLASS_STUDENT_LIST_FAIL';
export const FETCH_ALPS_CLASS_STUDENT_LIST_SUCCESS =
  'board/CourseDetailPage/FETCH_ALPS_CLASS_STUDENT_LIST_SUCCESS';
